databases:
  name: postgres
  ipAllowList: []

services:
  type: web
  name: rails
  env: ruby
  buildComand: "./bin/render-build.sh"
  startCommand: bundle exec rails s
  envVars:
    key: RAILS_MASTER_KEY
    sync: false
    key: DATABASE_URL
    framDatabase:
      name: postgres
      property: connectionString
    type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
